### ISSUE TITLE
Runtime render exception [TypeError: Cannot read properties of null (reading 'insertBefore')] after deploying

### ISSUE THREAD

**Issue by fingers10** [jsakamoto/BlazorWasmPreRendering.Build#36]
Hi @jsakamoto ,

I was deploying the published version and got the below runtime error. This error doesn't appear when I published the same blazor wasm project without this package. 

Error :
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read properties of null (reading 'insertBefore')
      TypeError: Cannot read properties of null (reading 'insertBefore')
          at x (https://localhost:44354/_framework/blazor.webassembly.js:1:17125)
          at M (https://localhost:44354/_framework/blazor.webassembly.js:1:16836)
          at se.insertComponent (https://localhost:44354/_framework/blazor.webassembly.js:1:24352)
          at se.insertFrame (https://localhost:44354/_framework/blazor.webassembly.js:1:23075)
          at se.applyEdits (https://localhost:44354/_framework/blazor.webassembly.js:1:21490)
          at se.updateComponent (https://localhost:44354/_framework/blazor.webassembly.js:1:20774)
          at https://localhost:44354/_framework/blazor.webassembly.js:1:59545
          at Vt.Ke._internal.renderBatch (https://localhost:44354/_framework/blazor.webassembly.js:1:59917)
          at Object.Gt [as invokeJSFromDotNet] (https://localhost:44354/_framework/blazor.webassembly.js:1:62760)
          at Object.Ii (https://localhost:44354/_framework/dotnet.7.0.10.uwx4ocxnwo.js:5:71974)
Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'insertBefore')
TypeError: Cannot read properties of null (reading 'insertBefore')
    at x (https://localhost:44354/_framework/blazor.webassembly.js:1:17125)
    at M (https://localhost:44354/_framework/blazor.webassembly.js:1:16836)
    at se.insertComponent (https://localhost:44354/_framework/blazor.webassembly.js:1:24352)
    at se.insertFrame (https://localhost:44354/_framework/blazor.webassembly.js:1:23075)
    at se.applyEdits (https://localhost:44354/_framework/blazor.webassembly.js:1:21490)
    at se.updateComponent (https://localhost:44354/_framework/blazor.webassembly.js:1:20774)
    at https://localhost:44354/_framework/blazor.webassembly.js:1:59545
    at Vt.Ke._internal.renderBatch (https://localhost:44354/_framework/blazor.webassembly.js:1:59917)
    at Object.Gt [as invokeJSFromDotNet] (https://localhost:44354/_framework/blazor.webassembly.js:1:62760)
    at Object.Ii (https://localhost:44354/_framework/dotnet.7.0.10.uwx4ocxnwo.js:5:71974)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String , Int32 , RenderBatch , Object , Int64 )
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String , Int32 , RenderBatch )
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

Screenshot :

![image](https://github.com/jsakamoto/BlazorWasmPreRendering.Build/assets/43729469/bf8e46fd-d087-4291-8d72-b657bd2f4a64)

Here is the sample repo link to reproduce above error - https://github.com/fingers10/PublishTest

Please let me know if any other additional details are needed.

Thanks,
fingers10

**Comment by fingers10** [comment]
@jsakamoto feel free to let me know if any other inputs are needed from my end.

**Comment by jsakamoto** [comment]
@fingers10 I figured out the reason for this issue, and I fixed it. I published the new version of this package, v.3.1.0 preview 3.

- https://www.nuget.org/packages/BlazorWasmPreRendering.Build/3.1.0-preview.3

Could you try it out? Again, thank you for your contributions to reporting.

**Comment by fingers10** [comment]
@jsakamoto This works. Now that I have updated "ilovedotnet" to above version. Published and deployed. It works
