### ISSUE TITLE
System.InvalidOperationException: 'RemoteNavigationManager' has not been initialized.

### ISSUE THREAD

**Issue by fingers10** [jsakamoto/BlazorWasmPreRendering.Build#48]
@jsakamoto I was integrating Identity Server to demonstrate OIDC flow in Blazor WASM and I go the below error during publish.

Here is the link of the GitHub Action - https://github.com/ILoveDotNet/ilovedotnet/actions/runs/12106569085/job/33752462279

```
Error: ROR] The HTTP status code was not OK. (it was (500)InternalServerError.)
      System.InvalidOperationException: 'RemoteNavigationManager' has not been initialized.
         at Microsoft.AspNetCore.Components.NavigationManager.AssertInitialized()
         at Microsoft.AspNetCore.Components.NavigationManager.ToAbsoluteUri(String relativeUri)
         at Microsoft.AspNetCore.Components.WebAssembly.Authentication.DefaultOidcOptionsConfiguration.Configure(RemoteAuthenticationOptions`1 options)
         at Microsoft.AspNetCore.Components.WebAssembly.Authentication.DefaultOidcOptionsConfiguration.PostConfigure(String name, RemoteAuthenticationOptions`1 options)
         at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1.CreateValue()
         at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
         at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3..ctor(IJSRuntime jsRuntime, IOptionsSnapshot`1 options, NavigationManager navigation, AccountClaimsPrincipalFactory`1 accountClaimsPrincipalFactory, ILogger`1 logger)
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
         at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
         at Toolbelt.Blazor.HeadElement.Middlewares.HeadElementServerPrerenderingMiddleware.InvokeAsync(HttpContext context, IHeadElementHelperStore store)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
      
      HEADERS
      =======
      Host: 127.0.0.1:[505](https://github.com/ILoveDotNet/ilovedotnet/actions/runs/12106569085/job/33752462279#step:13:506)0
      Accept-Language: en
      
  
  INFORMATION
  =============================
  The crawler encountered errors and/or warnings.
  
  TIPS
  -----------------------------
  If you want to keep running the pre-rendering server process for debugging it on live, you can do that by setting the "BlazorWasmPrerenderingKeepServer" MSBuild property to "true".
  
  ex) dotnet publish -p:BlazorWasmPrerenderingKeepServer=true
  
  Fetching complete.
```

Please can you assist me on this?

Thanks,
Abdul Rahman

**Comment by fingers10** [comment]
I suspect the below code and even moved it inside OnAfterRenderAsync

```razor
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication
@using Microsoft.Extensions.Options
@inject IOptionsSnapshot<RemoteAuthenticationOptions<ApiAuthorizationProviderOptions>> Options
@inject NavigationManager Navigation
 
@code {
    
    // This should be in onInitialized but it doesn't work during prerender publish in ci. Hence moving it to OnAfterRender
    @* protected override void OnInitialized()
    {
        Navigation.NavigateToLogin(Options.Get(Microsoft.Extensions.Options.Options.DefaultName).AuthenticationPaths.LogInPath);
    } *@

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            Navigation.NavigateToLogin(Options.Get(Microsoft.Extensions.Options.Options.DefaultName).AuthenticationPaths.LogInPath);
        }
    }
}
```

but still no luck

**Comment by jsakamoto** [comment]
Hi @fingers10,

The prerendering package supposes that the "ConfigureServices" method has no or only one string argument and that the string argument means the app's base address if there is one. The package doesn't suppose that the "ConfigureServices" method has two or more string parameters and can't determine those argument names. (The argument names of methods are usually minified at the publishing time.)

If you need to pass the environment name to the "ConfigureServices", please pass the "IWebAssemblyHostEnvironment" to its argument like this.

```cs
// Program.cs
...
ConfigureServices(builder.Services, builder.HostEnvironment, builder.Configuration);
...
static void ConfigureServices(IServiceCollection services, IWebAssemblyHostEnvironment webHostEnv, IConfiguration configuration)
{
    // You can get the environment name via "webHostEnv.Environment".
    ...
```

I sent a pull request to prove the solution.

- https://github.com/ILoveDotNet/ilovedotnet/pull/372

Thanks.

**Comment by fingers10** [comment]
Hi @jsakamoto the example shared by you works. Many thanks for your support and time. As a token of appreciation, I have updated the `README.md` to reflect this example.

Here is the PR for the same - https://github.com/jsakamoto/BlazorWasmPreRendering.Build/pull/49

Please validate and approve the post. I'm good to close this issue once the PR is approved.

**Comment by jsakamoto** [comment]
@fingers10 I merged the pull request you sent. That improved document must save time for other developers. Thank you for your contributions!
